spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true

jiguang:
  auth: NjgwNWYwYWFlYTI5NTIzMWQ1ZGZkMjQ5OmJkMjU0ODc5NjZmYTIxYmQxM2NhN2ZlYg==
  rsa:
    private:
      key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALR4MDERCTqGZys8ab9GLSWiKZRR34ZLTUoUwZTpfD7A2PgIXnG3ucox3T82B4C3Q/BFnAREiA7v35JHZtmL/CAC/M7hFt7TrBOG9OAQL/RFo6Qsjjk0uNNyTow4G0t+3QvXyK4faoUaOOP2fnkAt5APoy3nZhD9HDQset5VhyoHAgMBAAECgYASgqlevwKVUCfQ1Xd7OPV0gLeHEQa+PYcF7C8W2QP3Y8xdVG5rd47E4GxzCVWnrCR5xooEHgtejNf/pvczpRoM+kBeauouzTPEFgL0xdIZfSQwz/nAaN1Jazqwtb+POLuLTIwEUZBuSGScFXp3CbkkQwWNuA5Nyq68FGFM2zcKMQJBAOogFP9AxP5ADkTJhWxCO5sgwrO27dcv5VxxHij51mTE4FELxTUC3Rr8T+kG90pxAkoAtMo3Mfkcc61/ek865qMCQQDFVL23xNJV5TsKmnP5ggvexkqASLGPIbY8GNfW6JlsQBSsKZF9r1YCU1WXdkSxxl0rtOCkE03g3ZmIJU/ljLlNAkBdGcbfvhTX+gbyiaR56VikloF2T58CvDQb74uLxdXgmn2NHP4d13avPXhVdQSvYIMFhIRgCVTg99R0QMYVbZm7AkEAg0IH5Bo2ss4ExNvSMvBPBwMtAUHZYdTRzA3WXGxhyUCiv5Xy4gBkHK3j7BjOPtYsmWr6VglFL0MX4hi3mYBOrQJBAOm7fOwfsw1v6hdkz7qWOJVHvDbQsFJUsKji/pSknUkPDK9eG/+oIEqGbhXiyOB7v+kWfkf5ecOgK73MPq+ik6k=